name: Update Sidekiq Reliable Fetcher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' # Runs at 3 PM UTC daily (1 AM AEST)

jobs:
  fetch-gem:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this line to grant write permissions
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Sparse checkout sidekiq-reliable-fetch from GitLab
        run: |
          mkdir tmp && cd tmp
          git init
          git remote add origin https://gitlab.com/gitlab-org/gitlab.git
          git config core.sparseCheckout true
          echo "vendor/gems/sidekiq-reliable-fetch/*" >> .git/info/sparse-checkout
          git pull origin master --depth 1 # Added --depth 1 for efficiency

          cp -a vendor/gems/sidekiq-reliable-fetch/. ./ # Changed to cp -a to avoid EBUSY, copies all files
          
          # Remove now-empty folders and .git folder (optional)
          rm -rf vendor .git

          # Copy all content from current directory (tmp) to parent (project root)
          # Enable dotglob to include hidden files
          shopt -s dotglob
          cp -a ./* ../
          shopt -u dotglob
          
          # Return to project root
          cd ..
          # Remove the temporary directory, now empty
          rm -rf tmp

      - name: Commit changes
        run: |
          # Add all changes in the project root
          git add .
          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update project root with sidekiq-reliable-fetch from GitLab"
            git push
          fi
